### ISSUE TITLE
Cannot list notes

### ISSUE THREAD

**Issue by sschloesser** [a5huynh/cub-cli#9]
Hey there, thanks for providing this CLI! I, unfortunately, was unable to list notes and got the following error:
```
> RUST_BACKTRACE=1 cub ls
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(2, Null)', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: rusqlite::row::Row::get
  10: libcub::note::Note::from_sql
  11: <rusqlite::row::MappedRows<'conn, F> as core::iter::iterator::Iterator>::next
  12: <rusqlite::row::MappedRows<'conn, F> as core::iter::iterator::Iterator>::next
  13: libcub::list_notes
  14: cub::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
```

viewing individual notes with `cub show ###` does work as expected for me

**Comment by a5huynh** [comment]
Thanks for filing an issue, @sschloesser !

Looks like it got some data about a note that it wasn't expecting from the Bear database file. Do you have empty notes or anything like that?

**Comment by a5huynh** [comment]
Hey @sschloesser, I just pushed a small bugfix that should fix that error message above. 

Let me know if that fixes all issues with the `cub ls` command

**Comment by a5huynh** [comment]
Going to close this issue, let me know if you run into this issue again!

**Comment by sschloesser** [comment]
@a5huynh hey there, I pulled your fix and can verify that ls works as expected now!
